(function () {
  'use strict';

  var APP_VERSION = 'v0.1.0 24/07/2026';
  var CONFIG_KEY = 'cr40f.voucher.confirmacao.config.v1';
  var DEFAULT_CONFIG = {
    supportPhones: '+55 12 99723-6961 | +55 12 99615-9093',
    opsContact: 'deborah.keila@betinhos.com.br',
    commercialContact: 'junior@betinhos.com.br',
    financeContact: 'financeiro@betinhos.com.br',
    conciergeContact: 'CONTATO A DEFINIR',
    passengerCapacity: 'Até 4',
    luggageCapacity: 'Até 4',
    meetDriverText: 'No aeroporto, após retirar as bagagens, dirija-se ao ponto de encontro informado para o terminal. Nos hotéis e empresas, aguarde no lobby ou na recepção no horário programado.',
    mismatchText: 'Permaneça no local combinado e fale com nosso concierge. Nossa equipe acompanhará o atendimento e orientará o encontro com o motorista.',
    cancelPolicy: '[Espaço reservado para inserção do conteúdo aprovado da política de cancelamento.]'
  };
  var translations = {
    pt: { confirmExec:'CONFIRMAÇÃO EXECUTIVA', issuedLabel:'Emitido em', companyLabel:'Empresa', requesterLabel:'Solicitante', emailLabel:'E-mail', phoneLabel:'Telefone', passengerCountLabel:'Nº de passageiros', notesLabel:'Observações', operationPeriodLabel:'Período da operação', vehicleCardTitle:'Detalhes da Solicitação', categoryLabel:'Categoria', armorLabel:'Blindagem', passengerCapacityLabel:'Passageiros', luggageCapacityLabel:'Bagagens', operationsLabel:'Operação', commercialLabel:'Comercial', financeLabel:'Financeiro', scheduleTitle:'Programação', timezoneCaption:'HORÁRIO EM UTC BRASÍLIA', colOS:'OS', colDateTime:'Data/Horário', colRoute:'Trajeto', colFlight:'Dados do voo', meetDriverTitle:'Encontro com o motorista', mismatchTitle:'Em caso de desencontro', conciergeLabel:'Concierge:', footerLine1:'Este documento é uma confirmação operacional de reserva, não configurando orçamento, recibo ou nota fiscal.', footerLine2:'CONFIRA ATENTAMENTE OS DADOS DO ATENDIMENTO.', footerLine3:'As informações desta programação são tratadas exclusivamente para o planejamento e a execução dos serviços contratados.', footerSite:'betinhos.com.br', pageLabel:'Página', cancelPolicyTitle:'Política de Cancelamento' },
    en: { confirmExec:'EXECUTIVE CONFIRMATION', issuedLabel:'Issued on', companyLabel:'Company', requesterLabel:'Requested by', emailLabel:'Email', phoneLabel:'Phone', passengerCountLabel:'Passenger count', notesLabel:'Notes', operationPeriodLabel:'Operation period', vehicleCardTitle:'Request Details', categoryLabel:'Category', armorLabel:'Armor level', passengerCapacityLabel:'Passengers', luggageCapacityLabel:'Luggage', operationsLabel:'Operations', commercialLabel:'Commercial', financeLabel:'Finance', scheduleTitle:'Schedule', timezoneCaption:'TIME IN UTC BRASILIA', colOS:'Service #', colDateTime:'Date/Time', colRoute:'Route', colFlight:'Flight details', meetDriverTitle:'Meeting the driver', mismatchTitle:'If you cannot find your driver', conciergeLabel:'Concierge:', footerLine1:'This document is an operational reservation confirmation, and does not constitute a quote, receipt, or invoice.', footerLine2:'PLEASE REVIEW THE DETAILS CAREFULLY BEFORE THE SERVICE.', footerLine3:'The information in this schedule is used exclusively to plan and carry out the contracted services.', footerSite:'betinhos.com.br', pageLabel:'Page', cancelPolicyTitle:'Cancellation Policy' }
  };
  var state = { lang:'pt', config:loadConfig(), data:null };

  function getXrm() { if (window.Xrm) return window.Xrm; try { return window.parent !== window ? window.parent.Xrm : null; } catch (_) { return null; } }
  function getIds() { var raw = new URLSearchParams(window.location.search).get('ids') || ''; try { var parsed = JSON.parse(raw); return Array.isArray(parsed) ? parsed : [parsed]; } catch (_) { return raw.split(','); } }
  function cleanId(id) { return String(id || '').replace(/[{}]/g, '').trim(); }
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/[&<>'"]/g, function (char) { return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]; }); }
  function safeText(value, fallback) { var text = String(value == null ? '' : value).trim(); return text || (fallback || '—'); }
  function formatted(record, field) { return record[field + '@OData.Community.Display.V1.FormattedValue'] || ''; }
  function lookupName(record, field) { return formatted(record, '_' + field + '_value'); }
  function configKey() { var api = getXrm(); var userId = ''; try { userId = api && api.Utility && api.Utility.getGlobalContext().userSettings.userId || ''; } catch (_) {} return CONFIG_KEY + ':' + String(userId).replace(/[{}]/g, '').toLowerCase(); }
  function readConfig() { try { return Object.assign({}, DEFAULT_CONFIG, JSON.parse(localStorage.getItem(configKey()) || '{}')); } catch (_) { return Object.assign({}, DEFAULT_CONFIG); } }
  function loadConfig() { return readConfig(); }
  function saveConfig() { try { localStorage.setItem(configKey(), JSON.stringify(state.config)); } catch (_) {} }
  function dateBR(value, withTime) { if (!value) return '—'; var date = new Date(value); if (isNaN(date.getTime())) return safeText(value); return new Intl.DateTimeFormat('pt-BR', { timeZone:'America/Sao_Paulo', day:'2-digit', month:'2-digit', year:withTime ? undefined : 'numeric', hour:withTime ? '2-digit' : undefined, minute:withTime ? '2-digit' : undefined }).format(date); }
  function issuedNow() { return new Intl.DateTimeFormat('pt-BR', { timeZone:'America/Sao_Paulo', day:'2-digit', month:'2-digit', year:'numeric', hour:'2-digit', minute:'2-digit' }).format(new Date()); }
  function getField(record, field) { return record[field] || formatted(record, field) || ''; }
  function row(icon, label, value) { return '<div class="info-row"><span class="icon" aria-hidden="true">' + icon + '</span><span class="txt"><span class="lbl">' + escapeHtml(label) + ':</span>&nbsp;' + escapeHtml(safeText(value)) + '</span></div>'; }

  async function loadData() {
    var api = getXrm(); if (!api || !api.WebApi) throw new Error('Dataverse Client API indisponível.');
    var ids = getIds().map(cleanId).filter(function (id) { return /^[0-9a-f-]{36}$/i.test(id); });
    if (!ids.length) throw new Error('Nenhum serviço selecionado.');
    var fields = '$select=cr40f_reservadeveculosid,cr40f_id,cr40f_dataehorriodesada,cr40f_trajeto,cr40f_obsdeoperao,cr40f_email,cr40f_passageirosetelefonedecontato,cr40f_tipodeveiculo,_cr40f_cliente_value,_cr40f_solicitante_value,_cr40f_passageiro1_value,_cr40f_passageiro2_value,_cr40f_passageiro3_value,_cr40f_passageiro4_value,_cr40f_veiculo_value';
    var records = await Promise.all(ids.map(function (id) { return api.WebApi.retrieveRecord('cr40f_reservadeveculos', id, '?' + fields); }));
    var first = records[0];
    var passengers = [1,2,3,4].map(function (index) { return lookupName(first, 'cr40f_passageiro' + index); }).filter(Boolean);
    if (!passengers.length) passengers = ['—'];
    if (api.WebApi.retrieveMultipleRecords && first.cr40f_reservadeveculosid) {
      try {
        var links = await api.WebApi.retrieveMultipleRecords('cr40f_servicosporpassageiro', '?$select=_cr40f_bancodedados_value,cr40f_ordemdeselecao&$filter=_cr40f_geral_value eq ' + first.cr40f_reservadeveculosid + '&$orderby=cr40f_ordemdeselecao asc');
        var linkedPassengers = (links.entities || []).map(function (link) { return lookupName(link, 'cr40f_bancodedados'); }).filter(Boolean);
        if (linkedPassengers.length) passengers = linkedPassengers;
      } catch (_) {}
    }
    var category = getField(first, 'cr40f_tipodeveiculo');
    return { voucherNumber:'Voucher # ' + safeText(first.cr40f_id, first.cr40f_reservadeveculosid), issuedAt:issuedNow(), passengerNames:passengers.length ? passengers : ['—'], company:lookupName(first, 'cr40f_cliente'), requester:lookupName(first, 'cr40f_solicitante'), requesterEmail:safeText(first.cr40f_email), requesterPhone:safeText(first.cr40f_passageirosetelefonedecontato), passengerCount:passengers.length || '—', notes:first.cr40f_obsdeoperao, operationPeriod:period(records), vehicleCategory:category, armorLevel:/blindado/i.test(category) ? 'Sim' : '—', services:records.map(function (record) { return { os:safeText(record.cr40f_id, '—'), dateTime:dateBR(record.cr40f_dataehorriodesada, true), route:record.cr40f_trajeto, flightDisplay:'—' }; }) }; }
  function period(records) { var dates = records.map(function (record) { return new Date(record.cr40f_dataehorriodesada).getTime(); }).filter(function (time) { return !isNaN(time); }).sort(); if (!dates.length) return '—'; var first = new Date(dates[0]), last = new Date(dates[dates.length - 1]); return new Intl.DateTimeFormat('pt-BR', { timeZone:'America/Sao_Paulo', day:'2-digit', month:'2-digit', year:'numeric' }).format(first) + (dates.length > 1 ? ' – ' + new Intl.DateTimeFormat('pt-BR', { timeZone:'America/Sao_Paulo', day:'2-digit', month:'2-digit', year:'numeric' }).format(last) : ''); }
  function applyTranslations() { var t = translations[state.lang]; document.querySelectorAll('[data-t]').forEach(function (element) { element.textContent = t[element.getAttribute('data-t')] || ''; }); }
  function render() { var data = state.data, config = state.config, t = translations[state.lang]; applyTranslations(); document.getElementById('voucherNumber').textContent = data.voucherNumber; document.getElementById('voucherNumber2').textContent = data.voucherNumber; document.getElementById('issuedAt').textContent = data.issuedAt; document.getElementById('issuedAt2').textContent = data.issuedAt; document.getElementById('passengerNames').innerHTML = data.passengerNames.map(escapeHtml).map(function (name) { return '<div>' + name + '</div>'; }).join(''); document.getElementById('passengerInfoRows').innerHTML = row('▣',t.companyLabel,data.company)+row('◉',t.requesterLabel,data.requester)+row('@',t.emailLabel,data.requesterEmail)+row('☎',t.phoneLabel,data.requesterPhone)+row('♙',t.passengerCountLabel,data.passengerCount)+row('▤',t.notesLabel,data.notes)+row('▦',t.operationPeriodLabel,data.operationPeriod); document.getElementById('vehicleInfoRows').innerHTML = row('▣',t.categoryLabel,data.vehicleCategory)+row('◇',t.armorLabel,data.armorLevel)+row('♙',t.passengerCapacityLabel,config.passengerCapacity)+row('▱',t.luggageCapacityLabel,config.luggageCapacity); document.getElementById('supportInfoRows').innerHTML = row('☎',t.phoneLabel,config.supportPhones)+row('♙',t.operationsLabel,config.opsContact)+row('▣',t.commercialLabel,config.commercialContact)+row('$',t.financeLabel,config.financeContact); document.getElementById('scheduleBody').innerHTML = data.services.map(function (service, index) { return '<tr style="background:'+(index%2?'#f7f9fc':'#ffffff')+'"><td class="os">'+escapeHtml(service.os)+'</td><td>'+escapeHtml(service.dateTime)+'</td><td class="route">'+escapeHtml(safeText(service.route))+'</td><td class="flight">'+escapeHtml(service.flightDisplay)+'</td></tr>'; }).join(''); document.getElementById('meetDriverText').textContent = config.meetDriverText; document.getElementById('mismatchText').textContent = config.mismatchText; document.getElementById('conciergeContact').textContent = config.conciergeContact; document.getElementById('cancelPolicy').textContent = config.cancelPolicy; document.getElementById('toolbarStatus').textContent = data.services.length + (data.services.length === 1 ? ' serviço carregado' : ' serviços carregados'); document.getElementById('voucherPreview').hidden = false; document.getElementById('loadingState').hidden = true; document.querySelectorAll('.tool-button').forEach(function (button) { button.classList.toggle('is-active', button.id === 'btn-' + state.lang); }); }
  function bindSettings() { var form = document.getElementById('settingsForm'); Object.keys(state.config).forEach(function (key) { var field = form.elements[key]; if (field) field.value = state.config[key]; }); form.addEventListener('input', function (event) { if (!event.target.name) return; state.config[event.target.name] = event.target.value; saveConfig(); if (state.data) render(); }); document.getElementById('btn-settings').addEventListener('click', function () { var hidden = form.hasAttribute('hidden'); form.toggleAttribute('hidden', !hidden); this.setAttribute('aria-expanded', String(hidden)); this.textContent = hidden ? 'Ocultar' : 'Mostrar'; }); }
  function close() { window.parent.postMessage({ type:'cr40f-voucher-confirmacao:close' }, window.location.origin); }
  document.getElementById('btn-print').addEventListener('click', function () { window.print(); }); document.getElementById('btn-close').addEventListener('click', close); document.getElementById('btn-pt').addEventListener('click', function () { state.lang='pt'; render(); }); document.getElementById('btn-en').addEventListener('click', function () { state.lang='en'; render(); }); bindSettings(); loadData().then(function (data) { state.data=data; render(); }).catch(function (error) { document.getElementById('loadingState').hidden=true; document.getElementById('errorState').hidden=false; document.getElementById('errorState').textContent=error.message || 'Não foi possível carregar os serviços selecionados.'; });
}());
