var Cr40fVoucherConfirmacaoCommand = (function () {
  'use strict';
  var OVERLAY_ID = 'cr40f-voucher-confirmacao-native-overlay';
  var STYLE_ID = 'cr40f-voucher-confirmacao-native-overlay-style';
  var CLOSE_MESSAGE = 'cr40f-voucher-confirmacao:close';

  function getXrm() { if (window.Xrm) return window.Xrm; try { return window.parent !== window ? window.parent.Xrm : null; } catch (_) { return null; } }
  function normalizeIds(value) { var list = value; if (typeof value === 'string') { try { var parsed = JSON.parse(value); list = Array.isArray(parsed) ? parsed : value.split(','); } catch (_) { list = value.split(/[;,]/); } } if (!Array.isArray(list)) list = [list]; return list.map(function (item) { return typeof item === 'string' ? item : item && (item.Id || item.id); }).map(function (id) { return String(id || '').replace(/[{}]/g, '').trim(); }).filter(function (id) { return /^[0-9a-f-]{36}$/i.test(id); }); }
  function alert(text) { var api = getXrm(); return api && api.Navigation && api.Navigation.openAlertDialog ? api.Navigation.openAlertDialog({ title:'Voucher de confirmação', text:text }) : Promise.resolve(); }
  function openOverlay(ids) { var api = getXrm(); var hostWindow = window.top; var hostDocument = hostWindow.document; var existing = hostDocument.getElementById(OVERLAY_ID); if (existing) existing.remove(); var oldStyle = hostDocument.getElementById(STYLE_ID); if (oldStyle) oldStyle.remove(); var style = hostDocument.createElement('style'); style.id=STYLE_ID; style.textContent='#'+OVERLAY_ID+'{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;isolation:isolate;opacity:0;transition:opacity 180ms cubic-bezier(.23,1,.32,1)}#'+OVERLAY_ID+'.is-visible{opacity:1}#'+OVERLAY_ID+' .bt-voucher-backdrop{position:absolute;inset:0;background:rgba(0,26,61,.22);backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px)}#'+OVERLAY_ID+' iframe{position:relative;z-index:1;width:min(1480px,calc(100% - 48px));height:min(940px,calc(100% - 40px));border:0;border-radius:14px;background:transparent;box-shadow:none}@media(max-width:820px){#'+OVERLAY_ID+' iframe{width:100%;height:100%;border-radius:0}}'; var overlay=hostDocument.createElement('div'); overlay.id=OVERLAY_ID; overlay.setAttribute('role','dialog'); overlay.setAttribute('aria-modal','true'); overlay.setAttribute('aria-label','Voucher de confirmação'); var backdrop=hostDocument.createElement('div'); backdrop.className='bt-voucher-backdrop'; backdrop.setAttribute('aria-hidden','true'); var frame=hostDocument.createElement('iframe'); frame.title='Voucher de confirmação'; frame.setAttribute('allowtransparency','true'); var url=api.Utility.getGlobalContext().getClientUrl().replace(/\/$/,'')+'/WebResources/cr40f_VoucherConfirmacao.html?ids='+encodeURIComponent(JSON.stringify(ids))+'&cacheBust='+Date.now(); frame.src=url; overlay.appendChild(backdrop); overlay.appendChild(frame); (hostDocument.head||hostDocument.documentElement).appendChild(style); hostDocument.body.appendChild(overlay); var closed=false; function close(){if(closed)return;closed=true;hostWindow.removeEventListener('message',onMessage);hostWindow.removeEventListener('keydown',onKeyDown,true);overlay.classList.remove('is-visible');hostWindow.setTimeout(function(){overlay.remove();style.remove();},160);} function onMessage(event){if(event.origin!==hostWindow.location.origin||event.source!==frame.contentWindow||!event.data||event.data.type!==CLOSE_MESSAGE)return;close();} function onKeyDown(event){if(event.key==='Escape'){event.preventDefault();close();}} backdrop.addEventListener('mousedown',close); hostWindow.addEventListener('message',onMessage); hostWindow.addEventListener('keydown',onKeyDown,true); frame.addEventListener('load',function(){frame.focus();},{once:true}); hostWindow.requestAnimationFrame(function(){overlay.classList.add('is-visible');}); }
  function abrirVoucher(selectedItemIds) { var ids=normalizeIds(selectedItemIds); if(!ids.length)return alert('Selecione ao menos um serviço antes de abrir o voucher.'); openOverlay(ids); }
  return { abrirVoucher: abrirVoucher };
}());
